[package]
name = "jelly_jam"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
error-chain = "0.12.4"
log = "0.4.22"
log4rs = "1.3.0"
macroquad = { version = "0.3.23", default_features = false }
rodio = "0.20.1"
